const MAX_SLOTS=9,UNITS_PER_PAGE=4,STORAGE_KEY='g5n-patch-lab-v2';
let chain=[],patches=[],currentPatchId=1,editingSlotIdx=null,filterCat='ALL',searchQuery='',unitPage=0;
function deepClone(o){return JSON.parse(JSON.stringify(o))}
function showToast(msg,color){color=color||'var(--green)';let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.style.borderColor=color;t.style.color=color;t.style.boxShadow='0 0 20px '+color+'44';t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(function(){t.classList.remove('show')},2000)}
function saveToStorage(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({patches:patches,currentPatchId:currentPatchId}))}catch(e){}}
function loadFromStorage(){try{var r=localStorage.getItem(STORAGE_KEY);return r?JSON.parse(r):null}catch(e){return null}}
function init(){var s=loadFromStorage();if(s&&s.patches&&s.patches.length){patches=s.patches;currentPatchId=s.currentPatchId||patches[0].id}else{patches=DEFAULT_PATCHES.map(function(p){return deepClone(p)});currentPatchId=patches[0].id}loadPatch(currentPatchId)}
function loadPatch(id){var p=patches.find(function(x){return x.id===id});if(!p)return;currentPatchId=id;document.getElementById('currentPatchNum').textContent=String(id).padStart(3,'0');document.getElementById('patchNameInput').value=p.name;chain=p.chain.map(function(fx,i){return Object.assign({},deepClone(fx),{on:true,cat:p.cats[i]||'DRIVE'})});unitPage=0;renderAll();saveToStorage()}
function renderAll(){renderOverview();renderUnits();renderFootswitches();renderPatchList();updateSlotCount()}
function updateSlotCount(){var el=document.getElementById('slotCount');el.textContent=chain.length+'/'+MAX_SLOTS;el.style.color=chain.length>=MAX_SLOTS?'var(--red)':chain.length>=7?'var(--yellow)':'var(--accent2)'}
function renderOverview(){var el=document.getElementById('overviewChain'),html='';html+='<div class="ov-node io">GUITAR</div><span class="ov-arrow">→</span>';chain.forEach(function(fx,i){var ps=unitPage*UNITS_PER_PAGE,pe=ps+UNITS_PER_PAGE,act=i>=ps&&i<pe;html+='<div class="ov-node'+(act?' active':'')+(fx.on?'':' off')+'" onclick="focusUnit('+i+')">'+fx.name+'</div>';if(i<chain.length-1)html+='<span class="ov-arrow">→</span>'});if(chain.length)html+='<span class="ov-arrow">→</span>';html+='<div class="ov-node io out">AMP</div>';if(chain.length<MAX_SLOTS)html+='<button class="ov-add" onclick="addSlot()">+</button>';el.innerHTML=html;var tp=Math.max(1,Math.ceil(chain.length/UNITS_PER_PAGE));document.getElementById('unitPageLabel').textContent=(unitPage+1)+'/'+tp;document.getElementById('unitPagePrev').disabled=unitPage<=0;document.getElementById('unitPageNext').disabled=unitPage>=tp-1}
function shiftUnitPage(d){var tp=Math.max(1,Math.ceil(chain.length/UNITS_PER_PAGE));unitPage=Math.max(0,Math.min(tp-1,unitPage+d));renderOverview();renderUnits();renderFootswitches()}
function focusUnit(i){unitPage=Math.floor(i/UNITS_PER_PAGE);renderOverview();renderUnits();renderFootswitches()}
function renderUnits(){var el=document.getElementById('unitsGrid'),start=unitPage*UNITS_PER_PAGE,html='';for(var u=0;u<UNITS_PER_PAGE;u++){var i=start+u;if(i<chain.length)html+=makeUnitCard(chain[i],i);else if(i===chain.length&&chain.length<MAX_SLOTS)html+='<div class="unit-card empty" onclick="addSlot()"><div class="unit-empty-label"><span class="plus">+</span>ADD EFEITO</div></div>';else html+='<div class="unit-card empty" style="opacity:.25;cursor:default"><div class="unit-empty-label">—</div></div>'}el.innerHTML=html}
function makeUnitCard(fx,i){var html='<div class="unit-card'+(fx.on?' on':' off')+'">';html+='<div class="unit-header"><span class="unit-cat cat-'+(CAT_COLORS[fx.cat]||'drive')+'">'+(fx.cat||'')+'</span><button class="power-led '+(fx.on?'on':'')+'" onclick="toggleFx('+i+',event)"></button></div>';html+='<div class="unit-name">'+fx.name+'</div><div class="unit-knobs">';fx.params.slice(0,4).forEach(function(p,pi){var ind='';if(p.pedal)ind+='<span class="param-flag pedal">P</span>';if(p.tempo)ind+='<span class="param-flag tempo">♩</span>';var lab='<div class="knob-label" title="'+p.n+'">'+p.n+'</div>';if(p.options){var opt=p.options[p.v]||p.options[0];html+='<div class="knob-row">'+lab+'<div class="knob-select" id="ks-'+i+'-'+pi+'" onclick="cycleOption('+i+','+pi+')">'+opt+'</div>'+ind+'</div>'}else{var min=p.min!==undefined?p.min:0,range=p.max-min,pct=Math.round(((p.v-min)/range)*100);html+='<div class="knob-row">'+lab+'<div class="knob-track" onmousedown="startDrag(event,'+i+','+pi+')" ontouchstart="startDragTouch(event,'+i+','+pi+')"><div class="knob-fill" id="kf-'+i+'-'+pi+'" style="width:'+pct+'%"></div></div><div class="knob-val" id="kv-'+i+'-'+pi+'">'+p.v+'</div>'+ind+'</div>'}});if(fx.params.length>4)html+='<div class="params-more">+'+(fx.params.length-4)+' params</div>';html+='</div><div class="unit-actions"><button class="unit-action-btn" onclick="openPickerForSlot('+i+')">TROCAR</button><button class="unit-action-btn rm" onclick="removeSlot('+i+')">✕</button></div></div>';return html}
function renderFootswitches(){var el=document.getElementById('fsRow'),start=unitPage*UNITS_PER_PAGE,html='';for(var u=0;u<UNITS_PER_PAGE;u++){var i=start+u;if(i<chain.length){var fx=chain[i];html+='<button class="fs-btn'+(fx.on?' active':'')+'" onclick="toggleFx('+i+',event)">FS'+(u+1)+'<span class="fs-name">'+fx.name+'</span></button>'}else html+='<button class="fs-btn empty">FS'+(u+1)+'</button>'}el.innerHTML=html}
function cycleOption(idx,pidx){var p=chain[idx].params[pidx];if(!p.options)return;p.v=(p.v+1)%p.options.length;var el=document.getElementById('ks-'+idx+'-'+pidx);if(el)el.textContent=p.options[p.v]}
var dragging=null;
function startDrag(e,idx,pidx){dragging={idx:idx,pidx:pidx,startX:e.clientX,startV:chain[idx].params[pidx].v};e.preventDefault();document.addEventListener('mousemove',onDrag);document.addEventListener('mouseup',stopDrag)}
function startDragTouch(e,idx,pidx){var t=e.touches[0];dragging={idx:idx,pidx:pidx,startX:t.clientX,startV:chain[idx].params[pidx].v};e.preventDefault();document.addEventListener('touchmove',onDragTouch,{passive:false});document.addEventListener('touchend',stopDrag)}
function onDrag(e){if(dragging)updateDrag(e.clientX)}
function onDragTouch(e){if(!dragging)return;e.preventDefault();updateDrag(e.touches[0].clientX)}
function updateDrag(x){var idx=dragging.idx,pidx=dragging.pidx,p=chain[idx].params[pidx],min=p.min!==undefined?p.min:0,range=p.max-min,delta=(x-dragging.startX)*(range/120),nv=Math.round(Math.max(min,Math.min(p.max,dragging.startV+delta)));p.v=nv;var pct=Math.round(((nv-min)/range)*100),f=document.getElementById('kf-'+idx+'-'+pidx),v=document.getElementById('kv-'+idx+'-'+pidx);if(f)f.style.width=pct+'%';if(v)v.textContent=nv}
function stopDrag(){dragging=null;document.removeEventListener('mousemove',onDrag);document.removeEventListener('mouseup',stopDrag);document.removeEventListener('touchmove',onDragTouch);document.removeEventListener('touchend',stopDrag)}
function toggleFx(i,e){if(e)e.stopPropagation();if(i<0||i>=chain.length)return;chain[i].on=!chain[i].on;renderAll()}
function addSlot(){if(chain.length>=MAX_SLOTS){showToast('MÁXIMO DE '+MAX_SLOTS+' EFEITOS','var(--red)');return}editingSlotIdx=null;openModal()}
function removeSlot(i){chain.splice(i,1);var tp=Math.max(1,Math.ceil(chain.length/UNITS_PER_PAGE));if(unitPage>=tp)unitPage=Math.max(0,tp-1);renderAll()}
function clearChain(){if(!chain.length)return;chain=[];unitPage=0;renderAll();showToast('CADEIA LIMPA')}
function openPickerForSlot(i){editingSlotIdx=i;openModal()}
function openModal(){filterCat='ALL';searchQuery='';var s=document.getElementById('fxSearch');if(s)s.value='';document.getElementById('modalOverlay').classList.remove('hidden');setTimeout(function(){if(s)s.focus()},50);renderModalCats();renderFxGrid()}
function closeModal(){document.getElementById('modalOverlay').classList.add('hidden');editingSlotIdx=null;searchQuery=''}
function onFxSearch(v){searchQuery=(v||'').trim().toLowerCase();renderFxGrid()}
function renderModalCats(){var cats=['ALL'].concat(Object.keys(FX_DB)),el=document.getElementById('modalCats');el.innerHTML=cats.map(function(c){var n=c==='ALL'?Object.values(FX_DB).reduce(function(s,a){return s+a.length},0):FX_DB[c].length;return '<button class="cat-filter-btn '+(filterCat===c?'active':'')+'" onclick="setCat(\''+c+'\')">'+c+' <span class="cat-count">'+n+'</span></button>'}).join('')}
function setCat(c){filterCat=c;renderModalCats();renderFxGrid()}
function renderFxGrid(){var el=document.getElementById('fxGrid'),cats=filterCat==='ALL'?Object.keys(FX_DB):[filterCat],entries=[];cats.forEach(function(cat){FX_DB[cat].forEach(function(fx){entries.push(Object.assign({},fx,{cat:cat}))})});if(searchQuery)entries=entries.filter(function(fx){return fx.name.toLowerCase().indexOf(searchQuery)!==-1||(fx.desc&&fx.desc.toLowerCase().indexOf(searchQuery)!==-1)});if(!entries.length){el.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--muted);font-family:var(--mono)">NENHUM EFEITO ENCONTRADO</div>';return}el.innerHTML=entries.map(function(fx){var sn=fx.name.replace(/'/g,"\\'"),pn=fx.params.slice(0,4).map(function(p){return p.n}).join(', '),fl='';if(fx.params.some(function(p){return p.pedal}))fl+='<span class="param-flag pedal">P</span>';if(fx.params.some(function(p){return p.tempo}))fl+='<span class="param-flag tempo">♩</span>';return '<div class="fx-option" onclick="selectFx(\''+fx.cat+'\',\''+sn+'\')"><div class="fx-option-header"><span class="unit-cat cat-'+(CAT_COLORS[fx.cat]||'drive')+'">'+fx.cat+'</span>'+fl+'</div><div class="fx-option-name">'+fx.name+'</div><div class="fx-option-desc">'+fx.desc+'</div><div class="fx-option-params">'+pn+'</div></div>'}).join('')}
function selectFx(cat,name){var base=FX_DB[cat].find(function(f){return f.name===name});if(!base)return;var fx=Object.assign({},deepClone(base),{on:true,cat:cat});if(editingSlotIdx!==null){chain[editingSlotIdx]=fx;showToast('SLOT '+(editingSlotIdx+1)+' ATUALIZADO')}else{chain.push(fx);unitPage=Math.floor((chain.length-1)/UNITS_PER_PAGE);showToast(fx.name+' ADICIONADO')}closeModal();renderAll()}
function savePatch(){var name=(document.getElementById('patchNameInput').value.trim()||'PATCH').toUpperCase().slice(0,16),ex=patches.find(function(x){return x.id===currentPatchId}),data={id:currentPatchId,name:name,chain:chain.map(function(fx){var c=deepClone(fx);delete c.on;delete c.cat;return c}),cats:chain.map(function(fx){return fx.cat})};if(ex)Object.assign(ex,data);else patches.push(data);saveToStorage();renderPatchList();showToast('✓ PATCH SALVO')}
function deleteCurrentPatch(){patches=patches.filter(function(x){return x.id!==currentPatchId});if(patches.length)loadPatch(patches[0].id);else{chain=[];currentPatchId=1;document.getElementById('currentPatchNum').textContent='001';document.getElementById('patchNameInput').value='';unitPage=0;renderAll()}saveToStorage();showToast('PATCH EXCLUÍDO','var(--red)')}
function newPatch(){var maxId=patches.reduce(function(m,p){return Math.max(m,p.id)},0);currentPatchId=maxId+1;document.getElementById('currentPatchNum').textContent=String(currentPatchId).padStart(3,'0');document.getElementById('patchNameInput').value='';chain=[];unitPage=0;renderAll()}
function renderPatchList(){var el=document.getElementById('patchList'),html=patches.map(function(p){var a=p.id===currentPatchId?' active':'';return '<div class="patch-item'+a+'" onclick="loadPatch('+p.id+')"><div class="patch-num-small">'+String(p.id).padStart(3,'0')+'</div><div class="patch-item-info"><div class="patch-item-name">'+p.name+'</div><div class="patch-item-fx">'+(p.cats||[]).slice(0,3).join(' · ')+'</div></div></div>'}).join('');html+='<div class="patch-item new-patch" onclick="newPatch()"><div class="patch-num-small">+</div><div class="patch-item-info"><div class="patch-item-name">NOVO PATCH</div></div></div>';el.innerHTML=html}
document.addEventListener('DOMContentLoaded',function(){document.getElementById('modalOverlay').addEventListener('click',function(e){if(e.target===this)closeModal()});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal()});init()});
